### ISSUE TITLE
ditching libopenocm3

### ISSUE THREAD

**Issue by gimbas** [FFY00/openinput-cm3#6]
having quite a bit of trouble programming the rival 310 when using the firmware base on libopencm3, but i can do it just fine with my bare metal application https://github.com/gimbas/rival310-openfirm, i think it would be better t just ditch it and try to use it only for the usb implementation.

**Comment by FFY00** [comment]
Could you elaborate a bit on which issues you are running into?

**Comment by gimbas** [comment]
the main issue is not knowing exactly what is happening, i don't know how the startup is being handled, libopencm3 doesn't seem to have a linker for the the mcu in the rival310 and that is the root of the problem i think.
code doesn't run on the rival 310, when i debug trace the program counter is just lost somewhere random

**Comment by FFY00** [comment]
Yes, you need to add it yourself for the build system to work correctly. I need to fix that. libopencm3 only ships linker files for compatibility reasons, to get the linker file we should use the linker file generator they provide.

For a quick fix just add the following file to `/usr/arm-none-eabi/lib/stm32f103x6.ld`.

```ld
/* Linker script for STM32F103x8, 64k flash, 20k RAM. */

/* Define memory regions. */
MEMORY
{
	rom (rx) : ORIGIN = 0x08000000, LENGTH = 32K
	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 10K
}

/* Include the common ld script. */
INCLUDE cortex-m-generic.ld
```

**Comment by FFY00** [comment]
It shouldn't even be compiling if you use the `steelseries-rival310` target

**Comment by gimbas** [comment]
the only difference between the two is effectively the linker script, so i modified it manually to use my linker, but that didn't work, and i also tried the blue-pill target, since the memory map is practically the same it sould've worked

**Comment by FFY00** [comment]
No, it won't work. You need the correct linker file. I was able to get it working with the file I posted above.

I am going to make meson use the `genlink` script provided by libopencm3.

**Comment by gimbas** [comment]
It worked, i realize now why my linker didn't work, it's quite a bit more complicated, doesn't matter. I still think we would better off just developing with just the cmsis.

**Comment by FFY00** [comment]
We can re-evaluate later. If you want you can prototype in CMSIS.
